---
# file: ansible/sentry.yml
- hosts: headnode
  tasks:
    - name: Installing python-raven client package
      apt: name=python-raven state=present force=yes

    - name: Installing sentry config file
      template: src=templates/sentry_settings.j2 dest=/opt/ion/iondb/sentry_settings.py owner=www-data group=www-data mode=0664

    - name: Remove any previous sentry entries from local_settings.py
      shell: sed -i '/^# START ANSIBLE EDITED SENTRY BLOCK/,/# END ANSIBLE EDITED SENTRY BLOCK$/d' /opt/ion/iondb/local_settings.py

    - name: Adding START ANSIBLE EDITED SENTRY BLOCK local_settings.py
      lineinfile: dest=/opt/ion/iondb/local_settings.py
                    state=present create=yes backup=yes
                    insertafter=EOF
                    line="# START ANSIBLE EDITED SENTRY BLOCK"
    - name: Adding DEBUG_APPS entry to local_settings.py
      lineinfile: "dest='/opt/ion/iondb/local_settings.py'
                    insertafter='# START ANSIBLE EDITED SENTRY BLOCK'
                    line=\"DEBUG_APPS = ('raven.contrib.django.raven_compat',)  # Reports errors to sentry server\""
    - name:
      lineinfile: "dest=/opt/ion/iondb/local_settings.py
                    insertafter='DEBUG_APPS.*'
                    line='try:'"
    - name:
      lineinfile: "dest=/opt/ion/iondb/local_settings.py
                    insertafter='try:'
                    line='    from iondb.sentry_settings import *'"
    - name:
      lineinfile: "dest=/opt/ion/iondb/local_settings.py
                    insertafter='    from iondb.sentry_settings import *'
                    line='except ImportError:'"
    - name:
      lineinfile: "dest=/opt/ion/iondb/local_settings.py
                    insertafter='except ImportError:'
                    line='    pass'"
    - name: Update JS_EXTRA in local_settings.py
      lineinfile: dest=/opt/ion/iondb/local_settings.py
                    insertafter='    pass'
                    line='JS_EXTRA = True'
    - name: Adding END ANSIBLE EDITED SENTRY BLOCK local_settings.py
      lineinfile: dest=/opt/ion/iondb/local_settings.py
                    insertafter='JS_EXTRA = True'
                    line="# END ANSIBLE EDITED SENTRY BLOCK"

    - name: Overwriting /opt/ion/iondb/templates/rundb/common/js_extra.html
      template: src=files/js_extra.html dest=/opt/ion/iondb/templates/rundb/common/js_extra.html owner=www-data group=www-data mode=664 backup=yes
      ignore_errors: Yes

    - name: Restart apache2
      service: name=apache2 state=restarted
